name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Apply
        id: terraform_apply
        run: |
          terraform apply -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
          
          # Captura o IP público
          INSTANCE_IP=$(terraform output -raw instance_public_ip)
          if [ -z "$INSTANCE_IP" ]; then
            echo "Erro: Não foi possível obter o IP da instância."
            exit 1
          fi
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
          echo "::set-output name=instance_ip::$INSTANCE_IP"
        working-directory: ./infra

      - name: Export Private Key
        run: |
          terraform output -raw private_key_pem > $HOME/deployer_key.pem
          chmod 600 $HOME/deployer_key.pem
        working-directory: ./infra

      - name: Wait for SSH to be available
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          echo "Aguardando a instância estar acessível via SSH..."
          for i in {1..30}; do
            nc -zv $INSTANCE_IP 22 && break
            echo "Tentativa $i: Porta 22 ainda não está acessível. Aguardando 10 segundos..."
            sleep 10
          done
          if ! nc -zv $INSTANCE_IP 22; then
            echo "Erro: Porta 22 não está acessível após várias tentativas."
            exit 1
          fi
          echo "Porta 22 está acessível. Continuando com o deploy."

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        id: build
        run: |
          mvn clean package
          JAR_PATH=$(find target -name '*.jar')
          if [ -z "$JAR_PATH" ]; then
            echo "Erro: Nenhum arquivo JAR encontrado após a build."
            exit 1
          fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "Caminho do JAR: $JAR_PATH"

      - name: Deploy Application
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          KEY_PATH="$HOME/deployer_key.pem"
          JAR_PATH="${{ env.JAR_PATH }}"

          echo "Iniciando transferência do JAR com SCP..."
          scp -o "StrictHostKeyChecking=no" -i "$KEY_PATH" "$JAR_PATH" ec2-user@$INSTANCE_IP:/home/ec2-user/cliente-1.0-SNAPSHOT.jar
          echo "Arquivo JAR transferido com sucesso."

          echo "Configurando e iniciando a aplicação na instância EC2..."
          ssh -tt -o "StrictHostKeyChecking=no" -i "$KEY_PATH" ec2-user@$INSTANCE_IP << 'EOF'
          if [ ! -f "/home/ec2-user/cliente-1.0-SNAPSHOT.jar" ]; then
            echo "Erro: Arquivo JAR não encontrado."
            exit 1
          fi

          # Iniciar a aplicação
          nohup java -jar /home/ec2-user/cliente-1.0-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 &
          echo "Aplicação iniciada com sucesso. Logs estão disponíveis em /home/ec2-user/app.log"
          EOF
