name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Apply
        id: terraform_apply
        run: |
          terraform apply -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
          echo "::set-output name=instance_public_ip::$(terraform output -raw instance_public_ip)"
        working-directory: ./infra

      - name: Export Private Key
        run: |
          sudo terraform output -raw private_key_pem > $HOME/deployer_key.pem
        working-directory: ./infra

      - name: Deploy Application
        run: |
          instance_ip=${{ steps.terraform_apply.outputs.instance_public_ip }}
          KEY_PATH="$HOME/deployer_key.pem"

          # Verifique se o arquivo de chave privada existe
          if [ ! -f "$KEY_PATH" ]; then
            echo "Erro: Arquivo de chave privada não encontrado em $KEY_PATH."
            exit 1
          fi

          # Copie o JAR para a instância EC2
          scp -o "StrictHostKeyChecking=no" target/myapp.jar ec2-user@$instance_ip:/path/to/myapp.jar

          # Conecte-se à instância via SSH e execute o comando
          ssh -tt -o "StrictHostKeyChecking=no" -i "$KEY_PATH" ec2-user@$instance_ip << 'EOF'
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}

          # Verifique se o arquivo JAR existe
          if [ ! -f "/path/to/myapp.jar" ]; then
            echo "Erro: Arquivo JAR não encontrado em /path/to/myapp.jar."
            exit 1
          fi

          # Inicie a aplicação
          nohup java -jar /path/to/myapp.jar > /dev/null 2>&1 &
          EOF
        shell: bash
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}