name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Apply
        id: terraform_apply
        run: |
          terraform apply -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve

          RAW_INSTANCE_IP=$(terraform output -raw instance_public_ip || terraform output instance_public_ip)
          INSTANCE_IP=$(echo "$RAW_INSTANCE_IP" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)

          if [ -z "$INSTANCE_IP" ]; then
            echo "Erro: Não foi possível obter o IP da instância."
            exit 1
          fi
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
          echo "::set-output name=instance_ip::$INSTANCE_IP"
        working-directory: ./infra

      - name: Export Private Key
        run: |
          terraform output -raw private_key_pem > $HOME/deployer_key.pem
          chmod 600 $HOME/deployer_key.pem
        working-directory: ./infra

      - name: Wait for SSH to be available
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          for i in {1..30}; do
            nc -zv $INSTANCE_IP 22 && break
            echo "Tentativa $i: Porta 22 ainda não está acessível. Aguardando 10 segundos..."
            sleep 10
          done
          if ! nc -zv $INSTANCE_IP 22; then
            echo "Erro: Porta 22 não está acessível após várias tentativas."
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        id: build
        run: |
          mvn clean package
          JAR_PATH=$(find target -name '*.jar')
          if [ -z "$JAR_PATH" ]; then
            echo "Erro: Nenhum arquivo JAR encontrado após a build."
            exit 1
          fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Upload JAR to S3
        run: |
          aws s3 cp "${{ env.JAR_PATH }}" s3://tc-ec2-client-bucket/cliente-1.0-SNAPSHOT.jar
          echo "JAR copiado para o bucket com sucesso."

      - name: Deploy Application
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          KEY_PATH="$HOME/deployer_key.pem"

          if [ -z "$INSTANCE_IP" ]; then
            echo "Erro: IP da instância não encontrado."
            exit 1
          fi

          ssh -tt -o "StrictHostKeyChecking=no" -i "$KEY_PATH" ec2-user@$INSTANCE_IP << 'EOF'
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}

          TEMP_JAR_PATH="/tmp/cliente-1.0-SNAPSHOT.jar"
          aws s3 cp s3://tc-ec2-client-bucket/cliente-1.0-SNAPSHOT.jar $TEMP_JAR_PATH

          if [ ! -f "$TEMP_JAR_PATH" ]; then
            echo "Erro: Arquivo JAR não encontrado em $TEMP_JAR_PATH."
            exit 1
          fi

          nohup java -jar $TEMP_JAR_PATH > /dev/null 2>&1 &
          EOF
          echo "Aplicação iniciada com sucesso."