name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  test-and-validate:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and enforce JaCoCo coverage
        run: mvn verify
        env:
          MAVEN_OPTS: "-Djacoco.skip=false"

  deploy:
    runs-on: ubuntu-latest
    needs: [terraform, test-and-validate]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan

      - name: Deploy Application
        run: |
          ssh -o "StrictHostKeyChecking=no" ec2-user@<INSTANCE_IP> << 'EOF'
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          nohup java -jar /path/to/myapp.jar > /dev/null 2>&1 &
          EOF
