name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        id: build
        run: |
          mvn clean package
          JAR_PATH=$(find target -name '*.jar')
          if [ -z "$JAR_PATH" ]; then
            echo "Erro: Nenhum arquivo JAR encontrado após a build."
            exit 1
          fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Apply
        id: terraform_apply
        run: |
          terraform apply -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
          
          # Captura do IP público
          RAW_INSTANCE_IP=$(terraform output -raw instance_public_ip || terraform output instance_public_ip)
          INSTANCE_IP=$(echo "$RAW_INSTANCE_IP" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)

          if [ -z "$INSTANCE_IP" ]; then
            echo "Erro: Não foi possível obter o IP da instância."
            exit 1
          fi
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
          echo "::set-output name=instance_ip::$INSTANCE_IP"
        working-directory: ./infra

      - name: Export Private Key
        run: |
          terraform output -raw private_key_pem > $HOME/deployer_key.pem
          chmod 600 $HOME/deployer_key.pem
        working-directory: ./infra

      - name: Wait for SSH to be available
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          echo "Aguardando a instância estar acessível via SSH..."
          for i in {1..30}; do
            nc -zv $INSTANCE_IP 22 && break
            echo "Tentativa $i: Porta 22 ainda não está acessível. Aguardando 10 segundos..."
            sleep 10
          done
          if ! nc -zv $INSTANCE_IP 22; then
            echo "Erro: Porta 22 não está acessível após várias tentativas."
            exit 1
          fi
          echo "Porta 22 está acessível. Continuando com o deploy."

      - name: Deploy Application
        run: |
          INSTANCE_IP="${{ env.INSTANCE_IP }}"
          if [ -z "$INSTANCE_IP" ]; then
            echo "Erro: IP da instância não encontrado."
            exit 1
          fi
          echo "IP da instância: $INSTANCE_IP"

          KEY_PATH="$HOME/deployer_key.pem"
          JAR_PATH="${{ env.JAR_PATH }}"
          
          # Verifique se o arquivo de chave privada existe
          if [ ! -f "$KEY_PATH" ]; then
            echo "Erro: Arquivo de chave privada não encontrado em $KEY_PATH."
            exit 1
          fi
          echo "Arquivo de chave privada: $KEY_PATH"
          
          # Conecte-se à instância via SSH e execute o comando
          ssh -tt -o "StrictHostKeyChecking=no" -i "$KEY_PATH" ec2-user@$INSTANCE_IP << 'EOF'
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          echo "Sucesso! Conexão bem sucedida e variáveis de ambiente AWS configuradas."

          # Copie o JAR para a instância EC2
          echo "Copiando JAR para a instância..."
          scp -o "StrictHostKeyChecking=no" -i "$KEY_PATH" "$JAR_PATH" ec2-user@$INSTANCE_IP:/path/to/cliente-1.0-SNAPSHOT.jar

          # Verifique se o arquivo JAR existe
          if [ ! -f "/path/to/cliente-1.0-SNAPSHOT.jar" ]; then
            echo "Erro: Arquivo JAR não encontrado em /path/to/cliente-1.0-SNAPSHOT.jar."
            exit 1
          fi

          # Inicie a aplicação
          nohup java -jar /path/to/cliente-1.0-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF
          echo "Aplicação iniciada na instância."